export const events = [
    {
        id: 1,
        userid: 1,
        title: 'INSTITUTE INSIGHTS || THE TECHNOBER',
        desc: 'The Alumni Cell is proud to announce the Alumni Magazine IIT Indore 2019. Articles curated from our Alumni and students around different topics and categories. Enjoy reading the magazine and do let us know your feedback and views.',
        eventImg: 'post1.png',
        likes: 5,
        postDate: '1 hour ago',
        scheduleDate: '24 Dec 2021',
        upcoming: true,
    },
    {
        id: 2,
        userid: 2,
        title: 'Some national universities and organizations where IIT Indore Alumni are pursuing Masters’ or Ph.D. degrees',
        desc: 'The Alumni Cell is proud to announce the Alumni Magazine IIT Indore 2019. Articles curated from our Alumni and students around different topics and categories. Enjoy reading the magazine and do let us know your feedback and views.',
        eventImg: 'post2.jpg',
        likes: 5,
        postDate: '5 hours ago',
        scheduleDate: '24 Dec 2021',
        upcoming: true,
    },
    {
        id: 3,
        userid: 3,
        title: 'INSTITUTE INSIGHTS || THE TECHNOBER',
        desc: 'The Alumni Cell is proud to announce the Alumni Magazine IIT Indore 2019. Articles curated from our Alumni and students around different topics and categories. Enjoy reading the magazine and do let us know your feedback and views.',
        eventImg: '',
        likes: 5,
        postDate: '6 days ago',
        scheduleDate: '24 Dec 2021',
        upcoming: false,
    },
    {
        id: 4,
        userid: 2,
        title: 'INSTITUTE INSIGHTS || THE TECHNOBER',
        desc: 'The Alumni Cell is proud to announce the Alumni Magazine IIT Indore 2019. Articles curated from our Alumni and students around different topics and categories. Enjoy reading the magazine and do let us know your feedback and views.',
        eventImg: 'post2.jpg',
        likes: 5,
        postDate: '1 month ago',
        scheduleDate: '24 Dec 2021',
        upcoming: false,
    },
]